language: python

python:
    - "3.6"

install:
    - apt-get install -y --fix-missing \
        build-essential \
        cmake \
        gfortran \
        git \
        wget \
        curl \
        graphicsmagick \
        libgraphicsmagick1-dev \
        libatlas-dev \
        libavcodec-dev \
        libavformat-dev \
        libboost-all-dev \
        libgtk2.0-dev \
        libjpeg-dev \
        liblapack-dev \
        libswscale-dev \
        pkg-config \
        python3-dev \
        python3-numpy \
        software-properties-common \
        zip \
        && apt-get clean && rm -rf /tmp/* /var/tmp/*
        
    - mkdir -p dlib && \
        git clone -b 'v19.7' --single-branch https://github.com/davisking/dlib.git dlib/ && \
        cd  dlib/ && \
        python3 setup.py install --yes USE_AVX_INSTRUCTIONS && \
        cd

    - pip3 install -r requirements.txt
    - tests/init_peopleparser.sh

script:
    - python3 -m unittest tests.test_peopleparser
