language: python

python:
    - "3.6"

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y \
        build-essential \
        cmake \
        gfortran \
        git \
        wget \
        curl \
        graphicsmagick \
        libgraphicsmagick1-dev \
        libatlas-dev \
        libavcodec-dev \
        libavformat-dev \
        libboost-all-dev \
        libgtk2.0-dev \
        libjpeg-dev \
        liblapack-dev \
        libswscale-dev \
        pkg-config \
        python3-dev \
        python3-numpy \
        software-properties-common \
        zip

    - mkdir -p dlib
    - git clone -b 'v19.8' --single-branch https://github.com/davisking/dlib.git dlib
    - cd  dlib/
    - python3 setup.py install --yes USE_AVX_INSTRUCTIONS

install:
    - pip3 install -r requirements.txt
    - tests/init_peopleparser.sh

script:
    - python3 -m unittest tests.test_peopleparser
